#!/bin/sh

LLINSTALLURL=https://raw.github.com/riywo/App-llenv/master/llinstall
[[ -z $LLENV_ROOT ]] && export LLENV_ROOT=$HOME/llenv

if [ -z "$TMPDIR" ]; then
    if [ -d "/tmp" ]; then
        TMPDIR="/tmp"
    else
        TMPDIR="."
    fi
fi

cd $TMPDIR || exit 1

LLINSTALLLOCALINSTALLER="llinstall-$$"

echo
if type curl >/dev/null 2>&1; then
  LLINSTALLDOWNLOAD="curl -k -f -sS -Lo $LLINSTALLLOCALINSTALLER $LLINSTALLURL"
elif type wget >/dev/null 2>&1; then
  LLINSTALLDOWNLOAD="wget --no-check-certificate -nv -O $LLINSTALLLOCALINSTALLER $LLINSTALLURL"
else
  echo "Need wget or curl to use $0"
  exit 1
fi

clean_exit () {
  [ -f $LLINSTALLLOCALINSTALLER ] && rm $LLINSTALLLOCALINSTALLER
  exit $1
}

echo "## Download the latest llinstall"
$LLINSTALLDOWNLOAD || clean_exit 1

echo
echo "## Installing llinstall"
chmod +x $LLINSTALLLOCALINSTALLER
mv $LLINSTALLLOCALINSTALLER $LLENV_ROOT/bin/llinstall

echo
echo "## Done."
